<?php
$jobListings = [
  [
    'id' => 1,
    'user_id' => 1,
    'title' => 'Software Engineer',
    'description' => 'We are seeking a skilled software engineer to develop high-quality software solutions',
    'salary' => '90000',
    'tags' => 'development, coding, java, python',
    'company' => 'Tech Solutions Inc.',
    'address' => '123 Rizal Ave',
    'city' => 'Manila',
    'state' => 'Metro Manila',
    'phone' => '348-334-3949',
    'email' => 'info@techsolutions.com',
    'requirements' => 'Bachelors degree in Computer Science or related field, 3+ years of software development experience',
    'benefits' => 'Healthcare, professional growth, flexible work hours'
  ],
  [
    'id' => 2,
    'user_id' => 2,
    'title' => 'Marketing Specialist',
    'description' => 'We are looking for a Marketing Specialist to create and manage marketing campaigns',
    'salary' => '70000',
    'tags' => 'marketing, advertising',
    'company' => 'Marketing Pros',
    'address' => '456 Ayala Ave',
    'city' => 'Makati',
    'state' => 'Metro Manila',
    'phone' => '454-344-3344',
    'email' => 'info@marketingpros.com',
    'requirements' => 'Bachelors degree in Marketing or related field, experience in digital marketing',
    'benefits' => 'Health and dental benefits, paid time off, remote work options'
  ],
  [
    'id' => 3,
    'user_id' => 3,
    'title' => 'Web Developer',
    'description' => 'Join our team as a Web Developer and create amazing web applications',
    'salary' => '85000',
    'tags' => 'web development, programming',
    'company' => 'WebTech Solutions',
    'address' => '789 Cebu Business Park',
    'city' => 'Cebu City',
    'state' => 'Cebu',
    'phone' => '456-876-5432',
    'email' => 'info@webtechsolutions.com',
    'requirements' => 'Bachelors degree in Computer Science or related field, proficiency in HTML, CSS, JavaScript',
    'benefits' => 'Competitive salary, professional development opportunities, friendly work environment'
  ],
  [
    'id' => 4,
    'user_id' => 1,
    'title' => 'Data Analyst',
    'description' => 'We are hiring a Data Analyst to analyze and interpret data for insights',
    'salary' => '75000',
    'tags' => 'data analysis, statistics',
    'company' => 'Data Insights LLC',
    'address' => '101 IT Park',
    'city' => 'Cebu City',
    'state' => 'Cebu',
    'phone' => '444-555-5555',
    'email' => 'info@datainsights.com',
    'requirements' => 'Bachelors degree in Data Science or related field, strong analytical skills',
    'benefits' => 'Health benefits, remote work options, casual dress code'
  ],
  [
    'id' => 5,
    'user_id' => 2,
    'title' => 'Graphic Designer',
    'description' => 'Join our creative team as a Graphic Designer and bring ideas to life',
    'salary' => '70000',
    'tags' => 'graphic design, creative',
    'company' => 'CreativeWorks Inc.',
    'address' => '234 Bonifacio High Street',
    'city' => 'Taguig',
    'state' => 'Metro Manila',
    'phone' => '499-321-9876',
    'email' => 'info@creativeworks.com',
    'requirements' => 'Bachelors degree in Graphic Design or related field, proficiency in Adobe Creative Suite',
    'benefits' => 'Flexible work hours, creative work environment, opportunities for growth'
  ],
  [
    'id' => 6,
    'user_id' => 1,
    'title' => 'Data Scientist',
    'description' => 'We\'re looking for a Data Scientist to analyze complex data and generate insights',
    'salary' => '100000',
    'tags' => 'data science, machine learning',
    'company' => 'DataGenius Corp',
    'address' => '567 Davao IT Park',
    'city' => 'Davao City',
    'state' => 'Davao del Sur',
    'phone' => '684-789-1234',
    'email' => 'info@datagenius.com',
    'requirements' => 'Masters or Ph.D. in Data Science or related field, experience with machine learning algorithms',
    'benefits' => 'Competitive salary, remote work options, professional development'
  ],
];

return $jobListings;
